name: Build, Test and Release | Stable version
on:
  push:
    branches:
      release

permissions:
  id-token: write
  contents: write

jobs:
  release-stable:
    uses: ./.github/workflows/deploy_liveness.yml
    with:
      type: release
    secrets: inherit

