name: Build, Test and Release | Unstable version
on:
  push:
    branches:
      main

permissions:
  id-token: write
  contents: write

jobs:
  release-unstable:
    uses: ./.github/workflows/deploy_liveness.yml
    with:
      type: unstable
    secrets: inherit